{"zhuyejiekou": [  

{"name":"独播社","url":"http://35ys.cc/api.php/v1.vod"},
{"name":"特狗影视","url":"https://www.tegouys.com/xgapp.php/v2/"}, 
{"name":"月儿影视","url":"https://yue52.xyz/api.php/v1.vod"},
{"name":"小城影视","url":"http://app.269w.com/api.php/v1.vod"},
{"name":"开尔影院","url":"https://appx.uy07.com/api.php/v1.vod"},
{"name": "9e国语","url": "http://vod.9e03.com/lvdou_api.php/v1.vod"},
{"name":"看365","url":"https://www.kan365.xyz/api.php/app/"},
{"name":"迪迪","url":"http://dd88.icu:6080/xgapp.php/v2/"},
{"name":"4k狗影视","url":"http://4kdog.tk/api.php/app/"},
{"name":"影视大全","url":"http://app.269w.com/api.php/v1.vod"},
{"name":"影视大全2","url":"https://app.okmedcos.com/api.php/v1.vod"}, 
{"name":"天空影视1","url":"https://tkys.tv/xgapp.php/v1/"},
{"name":"天空影视2","url":"https://www.tkys.tv/xgapp.php/v2/"},
{"name":"360影院","url":"http://360yy.cn/api.php/app/"},
{"name":"U5影视","url":"https://appx.uy07.com/api.php/v1.vod"},
{"name":"影库","url":"https://yingkudy.com/lvdou_api.php/v1.vod"},
{"name":"爱酷影视","url":"https://www.zhanlangbu.com/ruifenglb_api.php/v1.vod"},
{"name":"粉象视界","url":"http://42.157.129.15:34444/lvdou_api.php/v1.vod"},
{"name":"益达影院","url":"http://luobu.yss6080.com/mogai_api.php/v1.vod"},
{"name":"爱电影","url":"https://www.idianying.com.cn/mogai_api.php/v1.vod"},
{"name":"269","url":"http://app.269w.com/api.php/v1.vod"},
{"name":"艾特影视","url":"https://www.aitee.cc/api.php/v1.vod"}, 
{"name":"比邻影视","url":"http://0hzy.cn:9990/mogai_api.php/v1.vod"},
{"name":"狐影TV","url":"https://www.foxhtv.com/api.php/v1.vod"},
{"name":"海玉影视","url":"https://tv2.hykjtv.cn/api.php/v1.vod"},
{"name":"佳佳影视","url":"https://www.jiajia.pub/api.php/v1.vod"},
{"name":"玖卿乐播","url":"https://vod.nqcode.cn/api.php/v1.vod"},
{"name":"可乐影视","url":"http://klyingshi.com/api.php/v1.vod"},
{"name":"麦穗影视","url":"http://b.maisui66.cn/api.php/v1.vod"},
{"name":"铭轩影视","url":"http://lz0716.com/api.php/v1.vod"},
{"name":"诺诺影视","url":"http://nnys.cuicanys.cn/lvdou_api.php/v1.vod"},
{"name":"全球星","url":"http://www.mzok.cn/api.php/v1.vod"},
{"name":"氢视频","url":"http://www.h1080p.com/api.php/tv.vod"},
{"name":"群鑫影视","url":"http://www.qunxinys.com/api.php/v1.vod"},
{"name":"万能影院","url":"http://app.wnvod.net/lvdou_api.php/v1.vod"},
{"name":"小猫咪","url":"http://vod.xiaomaomi.cc/mogai_api.php/v1.vod"},
{"name":"小七影视","url":"https://www.xiaoqi0.cn/cuican_api.php/v1.vod"},
{"name":"夕阳影视","url":"http://cms.seo-tv.work/mogai_api.php/v1.vod"},
{"name":"鑫总资源","url":"http://app.mmhkj.xyz/lvdou_api.php/v1.vod"},
{"name":"毅世纪影视","url":"http://www.ysjblog.top/api.php/v1.vod"},
{"name":"手指影院","url":"https://szys5678.com/mogai_api.php/v1.vod"},
{"name":"豆芽视频","url":"http://bdintv.cn/lvdou_api.php/v1.vod"}, 
{"name": "可乐影视","url": "http://klyingshi.com/api.php/v1.vod"},
{"name":"万能影院","url":"http://app.wnvod.net/lvdou_api.php/v1.vod"},
{"name":"夕阳影视","url":"http://cms.seo-tv.work/mogai_api.php/v1.vod"}, 
{"name":"小七影视","url":"https://www.xiaoqi0.cn/cuican_api.php/v1.vod"},
{"name":"好看影视","url":"https://app.okmedcos.com/api.php/v1.vod"},
{"name":"冷视TV","url":"https://len.tv/api.php/v1.vod"},
{"name":"阿里影视","url":"http://aliys.cn:90/api.php/v1.vod"},
{"name":"段友影视","url":"http://js.66app.me/api.php/app/"},
{"name":"渔渔影视","url":"http://luobo.yugenye.site/api.php/v1.vod"},
{"name":"艾特影视","url":"https://www.aitee.cc/api.php/v1.vod"},
{"name":"蒲公英视频","url":"http://www.pgy1.top/ruifenglb_api.php/v1.vod"},
{"name":"看剧吧","url":"http://app.ishen520.com/api.php/v1.vod"}], 


"caijizhan": [
{"name":"酷云77","url":"http://api.kunyu77.com/api.php"},
{"name":"*91麻豆","url":"https://91md.me/url.php"},
{"name":"*丝袜资源","url":"https://siwazyw.cc/url.php"},
{"name":"*秀色资源","url":"https://url.xiuseurl.com/url.php"},
{"name":"*探探资源","url":"https://urlttzy.com/url.php"},
{"name":"*色猫资源","url":"https://url.maozyurl.com/inc/urljson_vod.php"},
{"name":"*花魁资源","name":"*花魁资源","url":"https://caiji.huakuiurl.com/inc/urljson_vod.php"},
{"name":"*葡萄资源","name":"*葡萄资源","url":"https://url.putaozy.net/inc/urljson_vod.php"},
{"name":"*色窝资源","name":"*色窝资源","url":"https://sewozyurl.com/url.php"},
{"name":"*淫窝资源","name":"*淫窝资源","url":"https://url.yinwourl.com/url.php"},
{"name":"*SB资源","name":"*SB资源","type":0,"url":"http://www.shabizy.com:777/inc/sea"},
{"name":"*色屌丝资源","name":"*色屌丝资源","type":0,"url":"http://sdszyurl.com/home/cjurl/asbb/mc10"},
{"name":"*小姐姐资源","name":"*小姐姐资源","type":0,"url":"https://xjjzyurl.com/home/cjurl/askl/mc10"},
{"name":"*52AVAV","name":"*52AVAV","type":0,"url":"https://52zyurl.com/home/cjurl/asda/mc10"},
{"name":"*我要啪啪","name":"*我要啪啪","type":0,"url":"http://www.caiji21.com/home/cjurl/klkl/mc10"},
{"name":"*AV集中淫","name":"*AV集中淫","type":0,"url":"https://www.caiji22.com/home/cjurl/klp0/mc10"},
{"name":"*夜夜撸资源","name":"*夜夜撸资源","type":0,"url":"https://www.caiji23.com/home/cjurl/kls6/mc10"},
{"name":"*大屌丝资源","name":"*大屌丝资源","type":0,"url":"http://www.caiji24.com/home/cjurl/p0d2/mc10"},
{"name":"*咪咪资源","name":"*咪咪资源","type":0,"url":"http://www.caiji25.com/home/cjurl/p0as/mc10"},
{"name":"*鲍鱼AV","name":"*鲍鱼AV","type":0,"url":"http://caiji26.com/home/cjurl/p0g8/mc10"},
{"name":"*精工厂资源","name":"*精工厂资源","type":0,"url":"https://jgczyurl.com/home/cjurl/kld2/mc10"},
{"name":"*点点娱乐","name":"*点点娱乐","type":0,"url":"https://xx55zyurl.com/home/cjurl/ascf/mc10"},
//{"name":"*淫人妻资源","name":"*淫人妻资源","url":"http://www.yrqcaiji.com/home/cjurl/s6c7/mc10/vod/json"},
//{"name":"*小处女资源","name":"*小处女资源","url":"http://xcncaiji.com/home/cjurl/s6bb/mc10/vod/json"},
{"name":"*大MM资源","name":"*大MM资源","type":0,"url":"https://www.dmmurl.com/home/cjurl/asd2c7/mc10"},
{"name":"*黄瓜TV资源","name":"*黄瓜TV资源","type":0,"url":"https://www.caiji10.com/home/cjurl/cfs6/mc10"},
{"name":"*快播盒子资源","name":"*快播盒子资源","type":0,"url":"https://www.caiji09.com/home/cjurl/cfp0/mc10"},
{"name":"*大香蕉资源","name":"*大香蕉资源","type":0,"url":"https://www.caiji08.com/home/cjurl/cfkl/mc10"},
{"name":"*日本AV在线","name":"*日本AV在线","type":0,"url":"https://www.caiji07.com/home/cjurl/cfcf/mc10"},
{"name":"*久久热在线","name":"*久久热在线","type":0,"url":"https://www.caiji06.com/home/cjurl/cfbb/mc10"},
{"name":"*青青草视频","name":"*青青草视频","type":0,"url":"https://www.caiji05.com/home/cjurl/cfda/mc10"},
{"name":"*麻豆视频","name":"*麻豆视频","type":0,"url":"https://www.caiji04.com/home/cjurl/cfc7/mc10"},
{"name":"*一本道资源","name":"*一本道资源","type":0,"url":"https://www.caiji03.com/home/cjurl/cfg8/mc10"},
{"name":"*草榴视频","name":"*草榴视频","type":0,"url":"https://www.caiji02.com/home/cjurl/cfas/mc10"},
{"name":"*亚洲成人在线","name":"*亚洲成人在线","type":0,"url":"https://www.caiji01.com/home/cjurl/cfd2/mc10"},
{"name":"*天噜啦资源","name":"*天噜啦资源","type":0,"url":"http://www.987caiji.com/url/max.php"},
{"name":"*99资源","name":"*99资源","url":"http://99zy.pw/url.php"},
//{"name":"*99资源吧","name":"*99资源吧","url":"http://99zyba.com/url.php"},
{"name":"*酷豆资源","name":"*酷豆资源","url":"https://kudouzy.com/url.php"},
{"name":"*酷豆2","name":"*酷豆2","url":"https://url.kdurl.info/url.php"},
{"name":"*酷伦理","name":"*酷伦理","url":"https://url.kudian70.com/url.php"},
{"name":"*影库资源","name":"*影库资源","url":"https://url.ykurl.net/url.php"},
{"name":"*爱播资源","name":"*爱播资源","url":"https://cj.urlabzy.com/url.php"},
{"name":"*美少女资源","name":"*美少女资源","type":0,"url":"https://www.msnii.com/url/xml.php"},
{"name":"*淫水机资源","name":"*淫水机资源","type":0,"url":"https://www.xrbsp.com/url/xml.php"},
{"name":"*香奶儿资源","name":"*香奶儿资源","type":0,"url":"https://www.gdlsp.com/url/xml.php"},
{"name":"*白嫖资源","name":"*白嫖资源","type":0,"url":"https://www.kxgav.com/url/xml.php"},
{"name":"*小湿妹资源","name":"*小湿妹资源","type":0,"url":"https://www.afasu.com/url/xml.php"},
{"name":"*大地资源","name":"*大地资源","type":0,"url":"https://dadiurl.com/url.php"},
{"name":"*CK资源","name":"*CK资源","url":"http://www.feifei67.com/url.php"},
{"name":"*老鸭资源","name":"*老鸭资源","url":"https://url.urllyzy.com/url.php"},
{"name":"*花椒资源","name":"*花椒资源","url":"https://urlhjzy.com/url.php"},
{"name":"*乐播资源","name":"*乐播资源","url":"https://lburl9.com/url.php"},
{"name":"*博天堂","name":"*博天堂","type":0,"url":"http://bttcj.com/inc/surl.php"},
{"name":"*环亚资源","name":"*环亚资源","type":0,"url":"http://wmcj8.com/inc/surl.php"},
{"name":"*AVZY6888资源","name":"*AVZY6888资源","url":"http://m.7777688.com/inc/urljson.php"},
{"name":"*色色资源","name":"*色色资源","type":0,"url":"http://secj8.com/inc/surl.php"},
{"name":"*玖玖资源","name":"*玖玖资源","type":0,"url":"http://99zywcj.com/inc/surl.php"},
{"name":"*狼少年","name":"*狼少年","type":0,"url":"http://cjmygzy.com/inc/surl.php"},
{"name":"*佳丽资源","name":"*佳丽资源","url":"http://www.jializyzurl.com/url.php"},
{"name":"*番号资源","name":"*番号资源","url":"http://fhurl9.com/url.php"},
{"name":"*鲨鱼资源","name":"*鲨鱼资源","url":"https://shayuurl.com/url.php"},
{"name":"*速度资源","name":"*速度资源","type":0,"url":"http://www.ggmmzy.com:9999/inc"},
{"name":"乐播资源","url":"https://lbapi9.com/api.php"}, 
{"name":"老鸭资源","url":"https://api.apilyzy.com/api.php"},
{"name":"色窝资源","url":"https://sewozyapi.com/api.php"},

{"name":"私人影视","url":"http://204240.top:8899/api.php"},
{"name":"电视家","url":"http://mytvhome.xyz/api.php"},


{"name":"秀色资源","url":"https://api.xiuseapi.com/api.php"}],

"lunbo": [
{"name": "斗鱼","fanye": "aHR0cHM6Ly93d3cuZG91eXUuY29tL2dhcGkvcmtjL2RpcmVjdG9yeS9taXhMaXN0LzJfMjA4Lw==","qianzhui": "aHR0cDovL2VwZy4xMTIxMTQueHl6L2RvdXl1Lw=="},
{"name": "虎牙","fanye": "aHR0cHM6Ly93d3cuaHV5YS5jb20vY2FjaGUucGhwP209TGl2ZUxpc3QmZG89Z2V0TGl2ZUxpc3RCeVBhZ2UmZ2FtZUlkPTIxMzUmdGFnQWxsPTAmY2FsbGJhY2s9Z2V0TGl2ZUxpc3RKc29ucENhbGxiYWNrJnBhZ2U9","qianzhui": "aHR0cHM6Ly9lcGcuMTEyMTE0Lnh5ei9odXlhLw=="},
{"name": "哔哩","fanye": "aHR0cHM6Ly9hcGkubGl2ZS5iaWxpYmlsaS5jb20veGxpdmUvd2ViLWludGVyZmFjZS92MS9zZWNvbmQvZ2V0TGlzdD9wbGF0Zm9ybT13ZWImcGFyZW50X2FyZWFfaWQ9MTAmYXJlYV9pZD0zMyZzb3J0X3R5cGU9b25saW5lJnBhZ2U9","qianzhui": "aHR0cHM6Ly9lcGcuMTEyMTE0Lnh5ei9iaWxpLw=="},
{"name": "yy","fanye":"aHR0cHM6Ly93d3cueXkuY29tL21vcmUvcGFnZS5hY3Rpb24/Yml6PXNpbmcmc3ViQml6PWlkeCZwYWdlPQ==","qianzhui": "aHR0cHM6Ly93d3cueXkuY29t"},
{"name": "HY体育","fanye": "aHR0cHM6Ly93d3cuaHV5YS5jb20vY2FjaGUucGhwP209TGl2ZUxpc3QmZG89Z2V0TGl2ZUxpc3RCeVBhZ2UmZ2FtZUlkPTIzNTYmdGFnQWxsPTAmY2FsbGJhY2s9Z2V0TGl2ZUxpc3RKc29ucENhbGxiYWNrJnBhZ2U9","qianzhui": "aHR0cDovLzEyNC4yMjMuMjEyLjM4OjgzL2h1eWEv"},  
{"name": "秀儿","fanye": "aHR0cHM6Ly93d3cuaHV5YS5jb20vY2FjaGUucGhwP209TGl2ZUxpc3QmZG89Z2V0TGl2ZUxpc3RCeVBhZ2UmZ2FtZUlkPTE2NjMmdGFnQWxsPTAmY2FsbGJhY2s9Z2V0TGl2ZUxpc3RKc29ucENhbGxiYWNrJnBhZ2U9","qianzhui": "aHR0cDovLzEyNC4yMjMuMjEyLjM4OjgzL2h1eWEv"}],
//主解析是JSON直链的，可以添加多个，例如：http://xxx.com?url=#https://xxx.com?url= 用#号分割，最后一个后面不加#号。
"zhujiexi": "http://47.98.234.2:7768/api.php?url=#http://110.42.2.115:880/analysis/json/?uid=2100&my=fgjnoqstLMRUZ03489&url=#https://svip.rongxingvr.top/api/?key=wuM6hZbINH2KlmHEdY&url=#https://play.fuqizhishi.com/maotv/API.php?appkey=QQ172598364&url=#https://svip.spchat.top/api/?type=ys&key=bKemW41JnxmQb4l67h&url=#https://jx.hfyrw.com/mao.go?url=#http://27.124.4.42:4567/jhjson/ceshi.php?url=#https://svip.spchat.top/api/?type=ys&key=bKemW41JnxmQb4l67h&url=#https://api.m3u8.tv:5678/home/api?type=ys&uid=1931000&key=gktuvyzABEORSYZ135&url=#http://27.124.4.42:4567/jhjson/ceshi.php?url=#https://vip.nxflv.com/home/api?uid=701203&key=bltuyCEFKLTX013679&url=#http://api.vip123kan.vip/?url=#https://vip.rongxingvr.top/api/?type=ys&key=JJEZkZIhzkA4cUtBfR&url=#https://api.ldjx.cc/wp-api/getvodurl.php?token=1001&vid=#https://a.dxzj88.com/jxrrm/jiami.php?url=#https://sz.dxzj88.com/jxrjrm/jiaomi.php?url=#https://jx.mczdyw.com/xg.php?url=#https://www.aiaine.com/api/?key=kVqmG5dAQ5dZTcECw8&url=#https://svip.rongxingvr.top/api/?key=niBgMGXVdCQhsmeEBK&url=#https://app.iminna.com/jx/?url=#https://vvip.funsline.cn/api/?key=3xWfEoDf4V9p9Y20CR&url=#https://jhpc.manduhu.com/j1217.php?url=#http://103.40.240.46/jh/?url=#https://json.pangujiexi.com:12345/json.php?url=#http://www.youhuifuligou.com/json/?id=7&url=#https://json.hfyrw.com/mao.go?url=#https://vip.aiaine.com/api/?key=8FN8gNAySnvJiMllxZ&url=#https://json.5lp.net/json.php?url=#https://vip.rongxingvr.top/api/?key=JJEZkZIhzkA4cUtBfR&url=#https://api.m3u8.tv:5678/home/api?type=ys&uid=9105801&key=huwxFGILMOQSTUZ679&url=#https://languangyingshiziyuan.1080zy.top/longtengzy.php/?url=#https://aa.xkys.tv/json.php?url=#https://vip.aiaine.com/api/?key=fOWaGgFU45zlIjvbHI&url=#https://svip.iremind.me/api/?key=A5Db8HF8c8FSIOR6R1&url=#https://api.leduotv.com/wp-api/getvodurl.php?vid=#https://www.nxflv.com/?url=#https://jmwl.qd234.cn/v/?v=#http://1.117.152.239:39000/?url=#https://jx.zui.cm/?url=#https://jx.parwix.com:4433/player/?url=#https://jx.parwix.com:4433/player/analysis.php?v=#https://s.2tu.uk/?url=#https://xrm3u8.qd234.cn/?url=#https://jx.daiguaji.com/?url=#https://jx.58g8.com/1/?url=#https://vip.legendwhb.cn/m3u8.php?url=#https://vip.bljiex.com/?v=#https://jx.zui.cm/?url=#https://ys.ling00.cn/CL4K/?url=#https://app.okmedcos.com/4k/?url=",


// 备用解析 是常规格式的解析，可以添加多个，用#号分割，最后一个不加#号
//备用解析是常规格式的解析，可以添加多个，例如：http://xxx.com?url=#https://xxx.com?url= 用#号分割，最后一个后面不加#号。
"beiyongjiexi": "https://www.ckplayer.vip/jiexi/?url=#https://www.ckmov.vip/api.php?url=#https://www.h8jx.com/jiexi.php?url=#https://ckmov.ccyjjd.com/ckmov/?url=#https://api.jiexi.la/?url=#https://vip.laobandq.com/jiexi.php?url=#https://www.mtosz.com/m3u8.php?url=#https://jx.m3u8.tv/jiexi/?url=#https://www.playm3u8.cn/jiexi.php?url=#https://www.pangujiexi.cc/jiexi.php?url=#https://jx.xmflv.com/?url=#https://jx.we-vip.com/?url=#https://jx.973973.xyz/?url=#https://jx.mmkv.cn/tv.php?url=#####https://jx.bozrc.com:4433/player/?url=#https://www.1717yun.com/jx/ty.php?url=#https://jx.yparse.com/index.php?url=#https://jsap.attakids.com/?url=#https://jx.playerjy.com/?url=#https://www.administratorw.com/video.php?url=#https://jx.blbo.cc:4433/?url=#https://www.zqzdzj.com/label/v.html?url=",
"dianshizhibo": "https://raw.githubusercontents.com/qaz1371041/biubiu/master/biu/tv/.php",

//填写体育直播的网址链接
"tiyuzhibo": "https://m.zhibo8.net",

//填写播放地址过滤规则，中间用#号分割，不用填太多，默认的基本够用，主要是针对自定义的网站过滤的。
"guolvdizhi": "player.css#url=#cnzz.com#51.la",


//下面都不用动了，就把上面那些填写完成就OK了。
"wuqu": "aHR0cDovL3d3dy5kanV1LmNvbQ==",
"Home": {
"dy": {
"class": "全部$&class=#喜剧$&class=喜剧#爱情$&class=爱情#动作$&class=动作#枪战$&class=枪战#犯罪$&class=犯罪#惊悚$&class=惊悚#恐怖$&class=恐怖#悬疑$&class=悬疑#动画$&class=动画#家庭$&class=家庭#奇幻$&class=奇幻#魔幻$&class=魔幻#科幻$&class=科幻#战争$&class=战争#青春$&class=青春#剧情$&class=剧情#西部$&class=西部#纪录$&class=记录#音乐$&class=音乐#歌舞$&class=歌舞#运动$&class=运动#历史$&class=历史#武侠$&class=武侠#冒险$&class=冒险#传记$&class=传记#伦理$&class=伦理",
"area": "全部$&area=#内地$&area=内地#香港$&area=香港#美国$&area=美国#欧洲$&area=欧洲#韩国$&area=韩国#日本$&area=日本#泰国$&area=泰国#印度$&area=印度#其它$&area=其它",
"year": "全部$&lang=&year=#2022$&lang=&year=2022#2021$&lang=&year=2021#2020$&lang=&year=2020#2019$&lang=&year=2019#2018$&lang=&year=2018#2017$&lang=&year=2017#2016-2011$&lang=&year=2016#2010-2000$&lang=&year=2010#90年代$&lang=&year=90#80年代$&lang=&year=80#更早$&lang=&year=70"
},
"dsj": {
"class": "全部$&class=#古装$&class=古装#言情$&class=言情#武侠$&class=武侠#偶像$&class=偶像#家庭$&class=家庭#青春$&class=青春#都市$&class=都市#喜剧$&class=喜剧#战争$&class=战争#军旅$&class=军旅#谍战$&class=谍战#悬疑$&class=悬疑#罪案$&class=罪案#穿越$&class=穿越#宫廷$&class=宫廷#历史$&class=历史#神话$&class=神话#科幻$&class=科幻#年代$&class=年代#农村$&class=农村#商战$&class=商战#剧情$&class=剧情#奇幻$&class=奇幻",
"area": "全部$&area=#内地$&area=内地#香港$&area=香港#美国$&area=美国#英国$&area=英国#韩国$&area=韩国#日本$&area=日本#泰国$&area=泰国#台湾$&area=台湾#其它$&area=其它",
"year": "全部$&lang=&year=#2022$&lang=&year=2022#2021$&lang=&year=2021#2020$&lang=&year=2020#2019$&lang=&year=2019#2018$&lang=&year=2018#2017$&lang=&year=2017#2016-2011$&lang=&year=2016#2010-2000$&lang=&year=2010#90年代$&lang=&year=90#80年代$&lang=&year=80#更早$&lang=&year=70"
},
"zy": {
"class": "全部$&class=#表演$&class=表演#播报$&class=播报#访谈$&class=访谈#体验$&class=体验#养成$&class=养成#游戏$&class=游戏#亲子$&class=亲子#美食$&class=美食#情感$&class=情感#选秀$&class=选秀#益智$&class=益智#晚会$&class=晚会#音乐$&class=音乐#文化$&class=文化#喜剧$&class=喜剧#曲艺$&class=曲艺#职场$&class=职场#脱口秀$&class=脱口秀#真人秀$&class=真人秀#竞技$&class=竞技#体育$&class=体育#萌宠$&class=萌宠",
"area": "全部$&area=#内地$&area=内地#香港$&area=香港#美国$&area=美国#韩国$&area=韩国#日本$&area=日本#台湾$&area=台湾",
"year": "全部$&lang=&year=#2022$&lang=&year=2022#2021$&lang=&year=2021#2020$&lang=&year=2020#2019$&lang=&year=2019#2018$&lang=&year=2018#2017$&lang=&year=2017#2016-2011$&lang=&year=2016#2010-2000$&lang=&year=2010#90年代$&lang=&year=90#80年代$&lang=&year=80#更早$&lang=&year=70"
},
"dm": {
"class": "全部$&class=#搞笑$&class=搞笑#番剧$&class=番剧#国创$&class=国创#大电影$&class=大电影#热血$&class=热血#催泪$&class=催泪#治愈$&class=治愈#励志$&class=励志#机战$&class=机战#战斗$&class=战斗#恋爱$&class=恋爱#科幻$&class=科幻#奇幻$&class=奇幻#魔幻$&class=魔幻#推理$&class=推理#校园$&class=校园#日常$&class=日常#经典$&class=经典#历史$&class=历史#美食$&class=美食#职场$&class=职场#偶像$&class=偶像#泡面$&class=泡面#冒险$&class=冒险#竞技$&class=竞技#武侠$&class=武侠#玄幻$&class=玄幻",
"area": "全部$&area=#内地$&area=内地#日本$&area=日本#欧美$&area=欧美#其它$&area=其它",
"year": "全部$&lang=&year=#2022$&lang=&year=2022#2021$&lang=&year=2021#2020$&lang=&year=2020#2019$&lang=&year=2019#2018$&lang=&year=2018#2017$&lang=&year=2017#2016-2011$&lang=&year=2016#2010-2000$&lang=&year=2010#90年代$&lang=&year=90#80年代$&lang=&year=80#更早$&lang=&year=70"
}
},
//填写自定义内容，格式是 {自定义1},{自定义2},{自定义3} 一个花括号里面就是一个自定义接口内容  用，号分割  最后一个不加，号
"zidingyi": [
{"name": "乐猪影视",
"url": "http://www.lezhutv.com",
"User": "空",
"fenlei": "电视剧$/type/2-#电影$/type/1-#综艺$/type/3-#动漫$/type/4-#韩剧$/type/14-#美剧$/type/15-#其它$/type/16-",
"houzhui": ".html",
"shifouercijiequ": "0",
"jiequqian": "空",
"jiequhou": "空",
"jiequshuzuqian": "class=\"vbox\"",
"jiequshuzuhou": "</a>",
"tupianqian": "data-original=\"",
"tupianhou": "\"",
"biaotiqian": "title=\"",
"biaotihou": "\"",
"lianjieqian": "href=\"",
"lianjiehou": "\"",
"sousuoqian": "/search-pg-1-wd-",
"sousuohou": ".html",
"sousuohouzhui": "/detail/",
"ssmoshi": "1",
"sousuoshifouercijiequ": "0",
"jspic": "空",
"jsname": "空",
"jsid": "空",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "class=\"vbox\"",
"ssjiequshuzuhou": "</a>",
"sstupianqian": "data-original=\"",
"sstupianhou": "\"",
"ssbiaotiqian": "title=\"",
"ssbiaotihou": "\"",
"sslianjieqian": "href=\"",
"sslianjiehou": "\"",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": "class=\"list_block show\"",
"bfjiequshuzuhou": "</ul>",
"zhuangtaiqian": "class=\"yac\">",
"zhuangtaihou": "</p>",
"daoyanqian": "导演：</span>",
"daoyanhou": "</p>",
"zhuyanqian": "主演：</span>",
"zhuyanhou": "</p>",
"juqingqian": "class=\"tbox_js\">",
"juqinghou": "</div>",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空",
"bfyjiequhou": "空",
"bfyjiequshuzuqian": "<li>",
"bfyjiequshuzuhou": "</li>",
"bfbiaotiqian": "\">",
"bfbiaotihou": "</a>",
"bflianjieqian": "href=\"",
"bflianjiehou": "\""},


{"name": "厂长资源",
"url": "https://qianoo.cn",
"User": "空",
"fenlei": "电视剧$/dsj/page/#电影$/zuixindianying/page/#番剧$/fanju/page/#动漫$/dm/page/#国产剧$/gcj/page/#美剧$/meijutt/page/#韩剧$/hanjutv/page/",
"houzhui": "",
"shifouercijiequ": "0",
"jiequqian": "空",
"jiequhou": "空",
"jiequshuzuqian": "<li>",
"jiequshuzuhou": "</span>",
"tupianqian": "original=\"",
"tupianhou": "\"",
"biaotiqian": "alt=\"",
"biaotihou": "\"",
"lianjieqian": "qianoo.cn",
"lianjiehou": "\"",
"sousuoqian": "/xssearch?q=",
"sousuohou": "",
"sousuohouzhui": "/movie/",
"ssmoshi": "1",
"sousuoshifouercijiequ": "0",
"jspic": "pic",
"jsname": "name",
"jsid": "id",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "<li>",
"ssjiequshuzuhou": "</span>",
"sstupianqian": "original=\"",
"sstupianhou": "\"",
"ssbiaotiqian": "alt=\"",
"ssbiaotihou": "\"",
"sslianjieqian": "qianoo.cn",
"sslianjiehou": "\"",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": "class=\"paly_list",
"bfjiequshuzuhou": "</div>",
"zhuangtaiqian": "上映：<span>",
"zhuangtaihou": "</span>",
"daoyanqian": "<li>导演：",
"daoyanhou": "</li>",
"zhuyanqian": "<li>主演：",
"zhuyanhou": "</li>",
"juqingqian": "class=\"yp_context\">",
"juqinghou": "</div>",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空",
"bfyjiequhou": "空",
"bfyjiequshuzuqian": "<a",
"bfyjiequshuzuhou": "/a>",
"bfbiaotiqian": ">",
"bfbiaotihou": "<",
"bflianjieqian": "qianoo.cn",
"bflianjiehou": "\""},



{"name": "香蕉视频",
  "url": "http://xjxj88.xyz",
  "tihuan": "cnzz.com", 
  "User": "空", 
  "shouye": "1",

  "fenlei": "人妻熟女$/index.php/vod/type/id/1/page/#偷拍自拍$/index.php/vod/type/id/2/page/#港韩情色$/index.php/vod/type/id/3/page/#丝袜制服$/index.php/vod/type/id/4/page/#清纯少女$/index.php/vod/type/id/5/page/#辣妹大奶$/index.php/vod/type/id/34/page/#女同专属$/index.php/vod/type/id/35/page/#素人出演$/index.php/vod/type/id/36/page/#角色扮演$/index.php/vod/type/id/37/page/#成人动漫$/index.php/vod/type/id/38/page/#变态另类$/index.php/vod/type/id/39/page/", 
  "houzhui": ".html",

  "shifouercijiequ": "0", 
  "jiequqian": "空",
  "jiequhou": "空", 
  "jiequshuzuqian": "class=\"module-item-pic", 
  "jiequshuzuhou": "</div>",
  "tupianqian": "src=\"",
  "tupianhou": "\"",
  "biaotiqian": "title=\"", 
  "biaotihou": "\"",
  "lianjieqian": "href=\"", 
  "lianjiehou": "\"", 

  "sousuoqian": "/index.php/ajax/suggest?mid=1&wd=",
  "sousuohou": "&limit=500",
  "sousuohouzhui": "/voddetail/", 
  "ssmoshi": "0",
  "sousuoshifouercijiequ": "0",
  "jspic": "pic",
  "jsname": "name",
  "jsid": "id",
  "ssjiequqian": "空",
  "ssjiequhou": "空",
  "ssjiequshuzuqian": "空",
  "ssjiequshuzuhou": "空",
  "sstupianqian": "空",
  "sstupianhou": "空",
  "ssbiaotiqian": "空",
  "ssbiaotihou": "空",
  "sslianjieqian": "空",
  "sslianjiehou": "空",

  "bfshifouercijiequ": "0",
  "bfjiequqian": "空",
  "bfjiequhou": "空",
  "bfjiequshuzuqian": "class=\"scroll-content", 
  "bfjiequshuzuhou": "</div>", 

  "zhuangtaiqian": "TAG：</span>",
  "zhuangtaihou": "</div>",
  "daoyanqian": "导演：</span>",
  "daoyanhou": "</div>",
  "zhuyanqian": "主演：</span>",
  "zhuyanhou": "</div>",
  "juqingqian": "剧情：</span>",
  "juqinghou": "</div>",

  "bfyshifouercijiequ": "0", 
  "bfyjiequqian": "空", 
  "bfyjiequhou": "空", 
  "bfyjiequshuzuqian": "<a", 
  "bfyjiequshuzuhou": "/span>",
  "bfbiaotiqian": "<span>",
  "bfbiaotihou": "</span>", 
  "bflianjieqian": "href=\"",
  "bflianjiehou": "\""},



{"name": "香蕉综合资源",
"url": "https://www.2024xxj.com/",
"tihuan": "cnzz.com",
"User": "空",
"fenlei": "亚洲ＡＶ$/?ju=cqzy-cqzyfl-62-0#3D动漫$/?ju=cqzy-cqzyfl-66-0-#自拍偷拍$/?ju=cqzy-cqzyfl-63-0-#超清传媒$/?ju=cqzy-cqzyfl-64-0-#欧美ＡＶ$/?ju=cqzy-cqzyfl-65-0-#乱伦人妻$/?ju=cqzy-cqzyfl-67-0-#丝袜制服$/?ju=cqzy-cqzyfl-68-0#直播录播$/?ju=cqzy-cqzyfl-69-0-#SM另类$/?ju=cqzy-cqzyfl-70-0-#超清三级$/?ju=cqzy-cqzyfl-71-0#亚洲ＡＶ$/?ju=cqzy-cqzyfl-62-0#3D动漫$/?ju=cqzy-cqzyfl-66-0-#自拍偷拍$/?ju=cqzy-cqzyfl-63-0-#超清传媒$/?ju=cqzy-cqzyfl-64-0-#欧美ＡＶ$/?ju=cqzy-cqzyfl-65-0-#乱伦人妻$/?ju=cqzy-cqzyfl-67-0-#丝袜制服$/?ju=cqzy-cqzyfl-68-0#直播录播$/?ju=cqzy-cqzyfl-69-0-#SM另类$/?ju=cqzy-cqzyfl-70-0-#超清三级$/?ju=cqzy-cqzyfl-71-0",
"houzhui": ".html",
"shifouercijiequ": "0",
"jiequqian": "空",
"jiequhou": "空",
"jiequshuzuqian": "class=\"uk-width-1-5",
"jiequshuzuhou": "</div>",
"tupianqian": "data-original=\"",
"tupianhou": "\"",
"biaotiqian": "alt=\"",
"biaotihou": "\"",
"lianjieqian": "href=\"",
"lianjiehou": "\"",
"sousuoqian": "/?m=search-type-so-0.html&TXT=",
"sousuohou": "&submit=",
"sousuohouzhui": "/detail/",
"ssmoshi": "1",
"sousuoshifouercijiequ": "0",
"jspic": "空",
"jsname": "空",
"jsid": "空",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "class=\"uk-width-1-5",
"ssjiequshuzuhou": "</a>",
"sstupianqian": "src=\"",
"sstupianhou": "\"",
"ssbiaotiqian": "alt=\"",
"ssbiaotihou": "\"",
"sslianjieqian": "href=\"",
"sslianjiehou": "\"",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": "class=\"read-btn uk-margin-bottom",
"bfjiequshuzuhou": "</div>",
"zhuangtaiqian": "影片分类:<span>",
"zhuangtaihou": "</p>",
"daoyanqian": "更新时间:<span>",
"daoyanhou": "</p>",
"zhuyanqian": "class=\"data\">主演：",
"zhuyanhou": "</p>",
"juqingqian": "<h3",
"juqinghou": "</h3>",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空",
"bfyjiequhou": "空",
"bfyjiequshuzuqian": "<a",
"bfyjiequshuzuhou": "/a>",
"bfbiaotiqian": ">",
"bfbiaotihou": "<",
"bflianjieqian": "href=\"",
"bflianjiehou": "\""},

{"name": "香蕉综合资源",
"url": "https://www.2024xxj.com/",
"tihuan": "cnzz.com",
"User": "空",
"fenlei": "中文综合$/?ju=xxj-xxjfl-zwzh-0-#中文无码$/?ju=xxj-xxjfl-zwwm-0-#中文近亲$/?ju=xxj-xxjfl-zwjq-0-#中文护士$/?ju=xxj-xxjfl-zwhs-0-#中文师生$/?ju=xxj-xxjfl-zwss-0-#中文强奸$/?ju=xxj-xxjfl-zwqj-0-#DVR高清$/?ju=xxj-xxjfl-dvrgq-0#美女主播$/?ju=xxj-xxjfl-mnzb-0-#国产自拍$/?ju=xxj-xxjfl-gczp-0-#高清HD$/?ju=xxj-xxjfl-gqhd-0-#欧美大片$/?ju=xxj-xxjfl-omdp-0-#三级综合$/?ju=xxj-xxjfl-sjzh-0#无码中文字幕$/?ju=thlt-thltfl-1-0#有码中文字幕$/?ju=thlt-thltfl-2-0-#精品国产视频$/?ju=thlt-thltfl-3-0-#欧美高清视频$/?ju=thlt-thltfl-4-0#成人动漫动画$/?ju=thlt-thltfl-5-0#国产自拍$/?ju=99re-99refl-72-0#肛交$/?ju=99re-99refl-67-0-#口爆颜射$/?ju=99re-99refl-66-0-#潮吹$/?ju=99re-99refl-63-0#制服丝袜$/?ju=99re-99refl-65-0#一本道$/?ju=99re-99refl-59-0-#日本有码$/?ju=99re-99refl-58-0-#加勒比$/?ju=99re-99refl-57-0-#日本无码$/?ju=99re-99refl-56-0-#李宗瑞全集$/?ju=99re-99refl-55-0#中文字幕$/?ju=99re-99refl-54-0#会员认证作品$/?ju=99re-99refl-64-0-#欧美$/?ju=99re-99refl-53-0#东京热$/?ju=99re-99refl-68-0#小格式综合$/?ju=99re-99refl-69-0-#女主播系列$/?ju=99re-99refl-70-0-#成人动漫$//?ju=99re-99refl-71-0#SM性虐$/?ju=99re-99refl-73-0#韩国综合$/?ju=99re-99refl-74-0-#三级专区$//?ju=99re-99refl-75-0#VR专区$/?ju=99re-99refl-76-0#VIP专区$/?ju=fcw-fcwfl-vipzq-0#日本有码$/?ju=fcw-fcwfl-rbym-0-#日本无码$/?ju=fcw-fcwfl-rbwm-0-#偷拍系列$/?ju=fcw-fcwfl-tpxl-0#成人动漫$/?ju=fcw-fcwfl-crdm-0#国产自拍$/?ju=fcw-fcwfl-gczp-0-#韩国综合$/?ju=fcw-fcwfl-hgzh-0-#VR专区$/?ju=fcw-fcwfl-vrzq-0#欧美专区$/?ju=fcw-fcwfl-omzq-0#麻豆原创$/?ju=gccm-gccmfl-1-0#91制片厂$/?ju=gccm-gccmfl-2-0-#天美传媒$/?ju=gccm-gccmfl-3-0-#蜜桃传媒$/?ju=gccm-gccmfl-4-0-#港台三级$/?ju=gccm-gccmfl-17-0-#皇家华人$/?ju=gccm-gccmfl-5-0-#星空传媒$/?ju=gccm-gccmfl-6-0#精东影业$/?ju=gccm-gccmfl-7-0-#乐播传媒$/?ju=gccm-gccmfl-8-0-#乌鸦传媒$/?ju=gccm-gccmfl-9-0-#兔子先生$/?ju=gccm-gccmfl-10-0-#杏吧原创$/?ju=gccm-gccmfl-11-0#mini传媒$//?ju=gccm-gccmfl-12-0#大象传媒$/?ju=gccm-gccmfl-13-0#开心鬼传媒$/?ju=gccm-gccmfl-14-0#PsychoPorn$/?ju=gccm-gccmfl-15-0#糖心Vlgo$/?ju=gccm-gccmfl-16-0#亚洲ＡＶ$/?ju=cqzy-cqzyfl-62-0#3D动漫$/?ju=cqzy-cqzyfl-66-0-#自拍偷拍$/?ju=cqzy-cqzyfl-63-0-#超清传媒$/?ju=cqzy-cqzyfl-64-0-#欧美ＡＶ$/?ju=cqzy-cqzyfl-65-0-#乱伦人妻$/?ju=cqzy-cqzyfl-67-0-#丝袜制服$/?ju=cqzy-cqzyfl-68-0#直播录播$/?ju=cqzy-cqzyfl-69-0-#SM另类$/?ju=cqzy-cqzyfl-70-0-#超清三级$/?ju=cqzy-cqzyfl-71-0",
"houzhui": ".html",
"shifouercijiequ": "0",
"jiequqian": "空",
"jiequhou": "空",
"jiequshuzuqian": "class=\"uk-width-1-5",
"jiequshuzuhou": "</a>",
"tupianqian": "data-original=\"",
"tupianhou": "\"",
"biaotiqian": "alt=\"",
"biaotihou": "\"",
"lianjieqian": "href=\"",
"lianjiehou": "\"",
"sousuoqian": "/?m=search-type-so-0.html&TXT=",
"sousuohou": "&submit=",
"sousuohouzhui": "/detail/",
"ssmoshi": "1",
"sousuoshifouercijiequ": "0",
"jspic": "空",
"jsname": "空",
"jsid": "空",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "class=\"uk-width-1-5",
"ssjiequshuzuhou": "</a>",
"sstupianqian": "src=\"",
"sstupianhou": "\"",
"ssbiaotiqian": "alt=\"",
"ssbiaotihou": "\"",
"sslianjieqian": "href=\"",
"sslianjiehou": "\"",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": "class=\"read-btn uk-margin-bottom",
"bfjiequshuzuhou": "</div>",
"zhuangtaiqian": "影片分类:<span>",
"zhuangtaihou": "</p>",
"daoyanqian": "更新时间:<span>",
"daoyanhou": "</p>",
"zhuyanqian": "class=\"data\">主演：",
"zhuyanhou": "</p>",
"juqingqian": "<h3",
"juqinghou": "</h3>",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空",
"bfyjiequhou": "空",
"bfyjiequshuzuqian": "<a",
"bfyjiequshuzuhou": "/a>",
"bfbiaotiqian": ">",
"bfbiaotihou": "<",
"bflianjieqian": "href=\"",
"bflianjiehou": "\""},

{"name": "香蕉国产传媒",
"url": "https://www.2024xxj.com/",
"tihuan": "cnzz.com",
"User": "空",
"fenlei": "麻豆原创$/?ju=gccm-gccmfl-1-0#91制片厂$/?ju=gccm-gccmfl-2-0-#天美传媒$/?ju=gccm-gccmfl-3-0-#蜜桃传媒$/?ju=gccm-gccmfl-4-0-#港台三级$/?ju=gccm-gccmfl-17-0-#皇家华人$/?ju=gccm-gccmfl-5-0-#星空传媒$/?ju=gccm-gccmfl-6-0#精东影业$/?ju=gccm-gccmfl-7-0-#乐播传媒$/?ju=gccm-gccmfl-8-0-#乌鸦传媒$/?ju=gccm-gccmfl-9-0-#兔子先生$/?ju=gccm-gccmfl-10-0-#杏吧原创$/?ju=gccm-gccmfl-11-0#mini传媒$//?ju=gccm-gccmfl-12-0#大象传媒$/?ju=gccm-gccmfl-13-0#开心鬼传媒$/?ju=gccm-gccmfl-14-0#PsychoPorn$/?ju=gccm-gccmfl-15-0#糖心Vlgo$/?ju=gccm-gccmfl-16-0",
"houzhui": ".html",
"shifouercijiequ": "0",
"jiequqian": "空",
"jiequhou": "空",
"jiequshuzuqian": "class=\"uk-width-1-5",
"jiequshuzuhou": "</a>",
"tupianqian": "src=\"",
"tupianhou": "\"",
"biaotiqian": "alt=\"",
"biaotihou": "\"",
"lianjieqian": "href=\"",
"lianjiehou": "\"",
"sousuoqian": "/?m=search-type-so-0.html&TXT=",
"sousuohou": "&submit=",
"sousuohouzhui": "/detail/",
"ssmoshi": "1",
"sousuoshifouercijiequ": "0",
"jspic": "空",
"jsname": "空",
"jsid": "空",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "class=\"uk-width-1-5",
"ssjiequshuzuhou": "</a>",
"sstupianqian": "src=\"",
"sstupianhou": "\"",
"ssbiaotiqian": "alt=\"",
"ssbiaotihou": "\"",
"sslianjieqian": "href=\"",
"sslianjiehou": "\"",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": "class=\"read-btn uk-margin-bottom",
"bfjiequshuzuhou": "</div>",
"zhuangtaiqian": "影片分类:<span>",
"zhuangtaihou": "</p>",
"daoyanqian": "更新时间:<span>",
"daoyanhou": "</p>",
"zhuyanqian": "class=\"data\">主演：",
"zhuyanhou": "</p>",
"juqingqian": "<h3",
"juqinghou": "</h3>",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空",
"bfyjiequhou": "空",
"bfyjiequshuzuqian": "<a",
"bfyjiequshuzuhou": "/a>",
"bfbiaotiqian": ">",
"bfbiaotihou": "<",
"bflianjieqian": "href=\"",
"bflianjiehou": "\""},
 
{"name": "香蕉废柴网资源",
"url": "https://www.2024xxj.com/",
"tihuan": "cnzz.com",
"User": "空",
"fenlei": "VIP专区$/?ju=fcw-fcwfl-vipzq-0#日本有码$/?ju=fcw-fcwfl-rbym-0-#日本无码$/?ju=fcw-fcwfl-rbwm-0-#偷拍系列$/?ju=fcw-fcwfl-tpxl-0#成人动漫$/?ju=fcw-fcwfl-crdm-0#国产自拍$/?ju=fcw-fcwfl-gczp-0-#韩国综合$/?ju=fcw-fcwfl-hgzh-0-#VR专区$/?ju=fcw-fcwfl-vrzq-0#欧美专区$/?ju=fcw-fcwfl-omzq-0",
"houzhui": ".html",
"shifouercijiequ": "0",
"jiequqian": "空",
"jiequhou": "空",
"jiequshuzuqian": "class=\"uk-width-1-5",
"jiequshuzuhou": "</a>",
"tupianqian": "data-original=\"",
"tupianhou": "\"",
"biaotiqian": "alt=\"",
"biaotihou": "\"",
"lianjieqian": "href=\"",
"lianjiehou": "\"",
"sousuoqian": "/?m=search-type-so-0.html&TXT=",
"sousuohou": "&submit=",
"sousuohouzhui": "/detail/",
"ssmoshi": "1",
"sousuoshifouercijiequ": "0",
"jspic": "空",
"jsname": "空",
"jsid": "空",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "class=\"uk-width-1-5",
"ssjiequshuzuhou": "</a>",
"sstupianqian": "src=\"",
"sstupianhou": "\"",
"ssbiaotiqian": "alt=\"",
"ssbiaotihou": "\"",
"sslianjieqian": "href=\"",
"sslianjiehou": "\"",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": "class=\"read-btn uk-margin-bottom",
"bfjiequshuzuhou": "</div>",
"zhuangtaiqian": "影片分类:<span>",
"zhuangtaihou": "</p>",
"daoyanqian": "更新时间:<span>",
"daoyanhou": "</p>",
"zhuyanqian": "class=\"data\">主演：",
"zhuyanhou": "</p>",
"juqingqian": "<h3",
"juqinghou": "</h3>",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空",
"bfyjiequhou": "空",
"bfyjiequshuzuqian": "<a",
"bfyjiequshuzuhou": "/a>",
"bfbiaotiqian": ">",
"bfbiaotihou": "<",
"bflianjieqian": "href=\"",
"bflianjiehou": "\""},

{"name": "香蕉久久热资源",
"url": "https://www.2024xxj.com/",
"tihuan": "cnzz.com",
"User": "空",
"fenlei": "国产自拍$/?ju=99re-99refl-72-0#肛交$/?ju=99re-99refl-67-0-#口爆颜射$/?ju=99re-99refl-66-0-#潮吹$/?ju=99re-99refl-63-0#制服丝袜$/?ju=99re-99refl-65-0#一本道$/?ju=99re-99refl-59-0-#日本有码$/?ju=99re-99refl-58-0-#加勒比$/?ju=99re-99refl-57-0-#日本无码$/?ju=99re-99refl-56-0-#李宗瑞全集$/?ju=99re-99refl-55-0#中文字幕$/?ju=99re-99refl-54-0#会员认证作品$/?ju=99re-99refl-64-0-#欧美$/?ju=99re-99refl-53-0#东京热$/?ju=99re-99refl-68-0#小格式综合$/?ju=99re-99refl-69-0-#女主播系列$/?ju=99re-99refl-70-0-#成人动漫$//?ju=99re-99refl-71-0#SM性虐$/?ju=99re-99refl-73-0#韩国综合$/?ju=99re-99refl-74-0-#三级专区$//?ju=99re-99refl-75-0#VR专区$/?ju=99re-99refl-76-0",
"houzhui": ".html",
"shifouercijiequ": "0",
"jiequqian": "空",
"jiequhou": "空",
"jiequshuzuqian": "class=\"uk-width-1-5",
"jiequshuzuhou": "</a>",
"tupianqian": "data-original=\"",
"tupianhou": "\"",
"biaotiqian": "alt=\"",
"biaotihou": "\"",
"lianjieqian": "href=\"",
"lianjiehou": "\"",
"sousuoqian": "/?m=search-type-so-0.html&TXT=",
"sousuohou": "&submit=",
"sousuohouzhui": "/detail/",
"ssmoshi": "1",
"sousuoshifouercijiequ": "0",
"jspic": "空",
"jsname": "空",
"jsid": "空",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "class=\"uk-width-1-5",
"ssjiequshuzuhou": "</a>",
"sstupianqian": "src=\"",
"sstupianhou": "\"",
"ssbiaotiqian": "alt=\"",
"ssbiaotihou": "\"",
"sslianjieqian": "href=\"",
"sslianjiehou": "\"",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": "class=\"read-btn uk-margin-bottom",
"bfjiequshuzuhou": "</div>",
"zhuangtaiqian": "影片分类:<span>",
"zhuangtaihou": "</p>",
"daoyanqian": "更新时间:<span>",
"daoyanhou": "</p>",
"zhuyanqian": "class=\"data\">主演：",
"zhuyanhou": "</p>",
"juqingqian": "<h3",
"juqinghou": "</h3>",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空",
"bfyjiequhou": "空",
"bfyjiequshuzuqian": "<a",
"bfyjiequshuzuhou": "/a>",
"bfbiaotiqian": ">",
"bfbiaotihou": "<",
"bflianjieqian": "href=\"",
"bflianjiehou": "\""},

{"name": "香蕉资源",
"url": "https://www.2024xxj.com/",
"tihuan": "cnzz.com",
"User": "空",
"fenlei": "中文综合$/?ju=xxj-xxjfl-zwzh-0-#中文无码$/?ju=xxj-xxjfl-zwwm-0-#中文近亲$/?ju=xxj-xxjfl-zwjq-0-#中文护士$/?ju=xxj-xxjfl-zwhs-0-#中文师生$/?ju=xxj-xxjfl-zwss-0-#中文强奸$/?ju=xxj-xxjfl-zwqj-0-#DVR高清$/?ju=xxj-xxjfl-dvrgq-0#美女主播$/?ju=xxj-xxjfl-mnzb-0-#国产自拍$/?ju=xxj-xxjfl-gczp-0-#高清HD$/?ju=xxj-xxjfl-gqhd-0-#欧美大片$/?ju=xxj-xxjfl-omdp-0-#三级综合$/?ju=xxj-xxjfl-sjzh-0",
"houzhui": ".html",
"shifouercijiequ": "0",
"jiequqian": "空",
"jiequhou": "空",
"jiequshuzuqian": "class=\"uk-width-1-5",
"jiequshuzuhou": "</a>",
"tupianqian": "data-original=\"",
"tupianhou": "\"",
"biaotiqian": "alt=\"",
"biaotihou": "\"",
"lianjieqian": "href=\"",
"lianjiehou": "\"",
"sousuoqian": "/?m=search-type-so-0.html&TXT=",
"sousuohou": "&submit=",
"sousuohouzhui": "/detail/",
"ssmoshi": "1",
"sousuoshifouercijiequ": "0",
"jspic": "空",
"jsname": "空",
"jsid": "空",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "class=\"uk-width-1-5",
"ssjiequshuzuhou": "</a>",
"sstupianqian": "src=\"",
"sstupianhou": "\"",
"ssbiaotiqian": "alt=\"",
"ssbiaotihou": "\"",
"sslianjieqian": "href=\"",
"sslianjiehou": "\"",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": "class=\"read-btn uk-margin-bottom",
"bfjiequshuzuhou": "</div>",
"zhuangtaiqian": "影片分类:<span>",
"zhuangtaihou": "</p>",
"daoyanqian": "更新时间:<span>",
"daoyanhou": "</p>",
"zhuyanqian": "class=\"data\">主演：",
"zhuyanhou": "</p>",
"juqingqian": "<h3",
"juqinghou": "</h3>",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空",
"bfyjiequhou": "空",
"bfyjiequshuzuqian": "<a",
"bfyjiequshuzuhou": "/a>",
"bfbiaotiqian": ">",
"bfbiaotihou": "<",
"bflianjieqian": "href=\"",
"bflianjiehou": "\""},

{"name": "香蕉桃花资源",
"url": "https://www.2024xxj.com/",
"tihuan": "cnzz.com",
"User": "空",
"fenlei": "无码中文字幕$/?ju=thlt-thltfl-1-0#有码中文字幕$/?ju=thlt-thltfl-2-0-#精品国产视频$/?ju=thlt-thltfl-3-0-#欧美高清视频$/?ju=thlt-thltfl-4-0#成人动漫动画$/?ju=thlt-thltfl-5-0",
"houzhui": ".html",
"shifouercijiequ": "0",
"jiequqian": "空",
"jiequhou": "空",
"jiequshuzuqian": "class=\"uk-width-1-5",
"jiequshuzuhou": "</a>",
"tupianqian": "src=\"",
"tupianhou": "\"",
"biaotiqian": "alt=\"",
"biaotihou": "\"",
"lianjieqian": "href=\"",
"lianjiehou": "\"",
"sousuoqian": "/?m=search-type-so-0.html&TXT=",
"sousuohou": "&submit=",
"sousuohouzhui": "/detail/",
"ssmoshi": "1",
"sousuoshifouercijiequ": "0",
"jspic": "空",
"jsname": "空",
"jsid": "空",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "class=\"uk-width-1-5",
"ssjiequshuzuhou": "</a>",
"sstupianqian": "data-original=\"",
"sstupianhou": "\"",
"ssbiaotiqian": "alt=\"",
"ssbiaotihou": "\"",
"sslianjieqian": "href=\"",
"sslianjiehou": "\"",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": "class=\"read-btn uk-margin-bottom",
"bfjiequshuzuhou": "</div>",
"zhuangtaiqian": "影片分类:<span>",
"zhuangtaihou": "</p>",
"daoyanqian": "更新时间:<span>",
"daoyanhou": "</p>",
"zhuyanqian": "class=\"data\">主演：",
"zhuyanhou": "</p>",
"juqingqian": "<h3",
"juqinghou": "</h3>",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空",
"bfyjiequhou": "空",
"bfyjiequshuzuqian": "<a",
"bfyjiequshuzuhou": "/a>",
"bfbiaotiqian": ">",
"bfbiaotihou": "<",
"bflianjieqian": "href=\"",
"bflianjiehou": "\""},


{
  "name": "8K影视",
  "url": "http://vip.8kvod.com:888/",
  "User": "空",
  "shouye": "1",
  "fenlei": "电影$/t/1/#连续剧$/t/2/#综艺$/t/3/#动漫$/t/4/#体育$/t/41/",
  "houzhui": ".html",
  "shifouercijiequ": "0",
  "jiequqian": "空",
  "jiequhou": "空",
  "jiequshuzuqian": "class=\"myui-vodlist__box",
  "jiequshuzuhou": "</div>",
  "tupianqian": "data-original=\"",
  "tupianhou": "\"",
  "biaotiqian": "title=\"",
  "biaotihou": "\"",
  "lianjieqian": "href=\"",
  "lianjiehou": "\"",
  "sousuoqian": "/index.php/ajax/suggest?mid=1&wd=",
  "sousuohou": "&limit=500",
  "sousuohouzhui": "/voddetail/",
    "ssmoshi": "0",
  "sousuoshifouercijiequ": "0",
  "jspic": "pic",
  "jsname": "name",
  "jsid": "id",
  "ssjiequqian": "空",
  "ssjiequhou": "空",
  "ssjiequshuzuqian": "空",
  "ssjiequshuzuhou": "空",
  "sstupianqian": "空",
  "sstupianhou": "空",
  "ssbiaotiqian": "空",
  "ssbiaotihou": "空",
  "sslianjieqian": "空",
  "sslianjiehou": "空",

  "bfshifouercijiequ": "0",
  "bfjiequqian": "空",
  "bfjiequhou": "空",
  "bfjiequshuzuqian": "id=\"playlist",
  "bfjiequshuzuhou": "</ul>",
  "zhuangtaiqian": "分类：</span>",
  "zhuangtaihou": "</p>",
  "daoyanqian": "导演：</span>",
  "daoyanhou": "</p>",
  "zhuyanqian": "主演：</span>",
  "zhuyanhou": "</p>",
  "juqingqian": "简介：</span>",
  "juqinghou": "</p>",
  "bfyshifouercijiequ": "0",
  "bfyjiequqian": "空",
  "bfyjiequhou": "空",
  "bfyjiequshuzuqian": "<li",
  "bfyjiequshuzuhou": "</li>",
  "bfbiaotiqian": "\">",
  "bfbiaotihou": "</a>",
  "bflianjieqian": "href=\"",
  "bflianjiehou": "\""
},




{"name": "*聚优AV",
"url": "https://juyouav.com",
"tihuan": "https://www.2022xxj.com/",
"tihuan": "https://www.2024xxj.com/",
"User": "空",
"fenlei": "AV解说$/index.php/vod/type/id/1/page/#中文无码$/index.php/vod/type/id/52/page/#中文综合$/index.php/vod/type/id/51/page/#中文近亲$/index.php/vod/type/id/50/page/#中文护士$/index.php/vod/type/id/53/page/#中文师生$/index.php/vod/type/id/54/page/#中文强奸$/index.php/vod/type/id/55/page/#国产综合$/index.php/vod/type/id/56/page/#美女主播$/index.php/vod/type/id/57/page/#VR高清$/index.php/vod/type/id/58/page/#高清HD$/index.php/vod/type/id/59/page/#欧美大片$/index.php/vod/type/id/60/page/#三级综合$/index.php/vod/type/id/61/page/#麻豆原创$/index.php/vod/type/id/33/page/#91制片厂$/index.php/vod/type/id/34/page/#天美传媒$/index.php/vod/type/id/35/page/#蜜桃传媒$/index.php/vod/type/id/36/page/#皇家华人$/index.php/vod/type/id/37/page/#星空传媒$/index.php/vod/type/id/38/page/#精东影业$/index.php/vod/type/id/39/page/#乐播传媒$/index.php/vod/type/id/40/page/#乌鸦传媒$/index.php/vod/type/id/41/page/#兔子先生$/index.php/vod/type/id/42/page/#杏吧原创$/index.php/vod/type/id/43/page/#mini传媒$/index.php/vod/type/id/44/page/#大象传媒$/index.php/vod/type/id/45/page/#开心鬼传媒$/index.php/vod/type/id/46/page/#PsychoPorn$/index.php/vod/type/id/47/page/#糖心Vlgo$/index.php/vod/type/id/48/page/#港台三级$/index.php/vod/type/id/49/page/#国产自拍一区$/index.php/vod/type/id/19/page/#肛交$/index.php/vod/type/id/2/page/#口爆颜射$/index.php/vod/type/id/3/page/#潮吹$/index.php/vod/type/id/4/page/#会员认证作品$/index.php/vod/type/id/5/page/#制服丝袜$/index.php/vod/type/id/6/page/#一本道$/index.php/vod/type/id/7/page/#高清$/index.php/vod/type/id/8/page/#日本有码$/index.php/vod/type/id/9/page/#加勒比$/index.php/vod/type/id/10/page/#日本无码$/index.php/vod/type/id/11/page/#李宗瑞全集$/index.php/vod/type/id/12/page/#中文字幕$/index.php/vod/type/id/13/page/#欧美$/index.php/vod/type/id/14/page/#东京热$/index.php/vod/type/id/15/page/#小格式综合$/index.php/vod/type/id/16/page/#女主播系列$/index.php/vod/type/id/17/page/#成人动漫$/index.php/vod/type/id/18/page/#SM性虐$/index.php/vod/type/id/20/page/#韩国综合$/index.php/vod/type/id/21/page/#三级片$/index.php/vod/type/id/22/page/#VR专区$/index.php/vod/type/id/23/page/#国产自拍二区$/index.php/vod/type/id/29/page/#VIP专区$/index.php/vod/type/id/24/page/#日本有码$/index.php/vod/type/id/25/page/#日本无码$/index.php/vod/type/id/26/page/#偷拍系列$/index.php/vod/type/id/27/page/#成人动漫$/index.php/vod/type/id/28/page/#韩国综合$/index.php/vod/type/id/30/page/#VR专区$/index.php/vod/type/id/31/page/#欧美$/index.php/vod/type/id/32/page/",
"houzhui": ".html",
"shifouercijiequ": "0",
"jiequqian": "空",
"jiequhou": "空",
"jiequshuzuqian": "class=\"uk-width-1-5",
"jiequshuzuhou": "</a>",
"tupianqian": "data-original=\"",
"tupianhou": "\"",
"biaotiqian": "alt=\"",
"biaotihou": "\"",
"lianjieqian": "href=\"",
"lianjiehou": "\"",
"sousuoqian": "/?m=search-type-so-0.html&TXT=",
"sousuohou": "&submit=",
"sousuohouzhui": "/detail/",
"ssmoshi": "1",
"sousuoshifouercijiequ": "0",
"jspic": "空",
"jsname": "空",
"jsid": "空",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "class=\"uk-width-1-5",
"ssjiequshuzuhou": "</a>",
"sstupianqian": "src=\"",
"sstupianhou": "\"",
"ssbiaotiqian": "alt=\"",
"ssbiaotihou": "\"",
"sslianjieqian": "href=\"",
"sslianjiehou": "\"",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": "class=\"read-btn uk-margin-bottom",
"bfjiequshuzuhou": "</div>",
"zhuangtaiqian": "影片分类:<span>",
"zhuangtaihou": "</p>",
"daoyanqian": "更新时间:<span>",
"daoyanhou": "</p>",
"zhuyanqian": "主演：",
"zhuyanhou": "</p>",
"juqingqian": "剧情：",
"juqinghou": "</p>",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空",
"bfyjiequhou": "空",
"bfyjiequshuzuqian": "<a",
"bfyjiequshuzuhou": "/a>",
"bfbiaotiqian": ">",
"bfbiaotihou": "<",
"bflianjieqian": "href=\"",
"bflianjiehou": "\""}


]
} 
